### PR TITLE
add preference item to disable edge-tiling at top of screen

### PR DESCRIPTION
**Pull request by dberner**
I prefer not to have top edge tiling active because I trigger it accidentally a lot and it becomes annoying. 

Added an option in the extension settings to disable (default on).

### CODE REVIEW

**Comment by dberner** [comment]
@ddnexus :  I updated to the current master, 394c1fd, with the smaller EDGE_ZONE_WIDTH, but it's still triggering unintentionally.  

It's the Fitts' law thing, the top edge is infinite so when I move a window up, an accidental trigger is likely. In Unity you could just turn it off for the top edge.

**Comment by ddnexus** [comment]
Yeah. That's because that _is not_  my original PR #59 commit (please read my last comment in #59), but the one modified by @emasab with an edited `EDGE_ZONE_WIDTH = 5`. Please, edit the `EDGE_ZONE_WIDTH = 1` and let us know if it works as you would like.

**Comment by dberner** [comment]
It's easier to control when set to 1, but I still prefer an option to turn it off entirely. I don't have accidental trigger because I can back out more easily but I still have the preview flashing at me when I don't want it to.

**Comment by ddnexus** [comment]
Does "easier to control when set to 1" means that the unwanted behavior can
still be triggered accidentally or not?

**Comment by ddnexus** [comment]
@dberner: sorry, I just read that you "don't have accidental trigger" with `EDGE_ZONE-WIDTH = 1` . Thanks.
@emasab: It looks like the 5 in place of 1 still causes problems. Please, reconsider the `EDGE_ZONE-WIDTH = 1`. Thanks.

**Comment by emasab** [comment]
Sorry but I cannot accept this pull request, I've added an option to disable edge tiling entirely and set EDGE_ZONE_WIDTH to 1 . This is too specific for the behavior you want and I've not received this request of disabling only the top edge tiling from other people. If I accept this I could receive other requests for disabling only the left edge tiling, the right one etc.

**Pull request closed without merging**
