### PR TITLE
Update for gnome 3.30

### LINKED ISSUE #66: Not working at all on Gnome 3.30
Just updated gnome to the latest version (still having an X11 session) and tried to use tiling, but it's not working at all.

I tried to debug a bit and the only thing that seemed wrong was the use of `global.screen` which seems to be deleted in 3.30, so I changed all `global.screen` to `global.display`, but that didn't work either.

If I got some time, I'll look further into the problem...

### PR DESCRIPTION
**Pull request by martin31821**
This PR updates the extension to the gnome 3.30 API, I don't know since which gnome shell version the API I used exists.

Furthermore I removed whitespaces in empty lines.
This PR fixes #66

### CODE REVIEW

**Comment by AlexWayfer** [comment]
> Furthermore I removed whitespaces in empty lines.

Please, add an [EditorConfig](https://editorconfig.org/) file, or this situation will be repeated with a more probability.

**Comment by martin31821** [comment]
> Please, add an [EditorConfig](https://editorconfig.org/) file, or this situation will be repeated with a more probability.

I definitiely agree with you here, but that should be done by the maintainer.

**Comment by emasab** [comment]
Thanks, I'm going to copy your changes, add a tiny compatibility class for previous versions and at the end add an EditorConfig to facilitate contributions. I'll do the compatibility checks with duck typing, I think It's the safest way

**Comment by emasab** [comment]
changes included in https://github.com/emasab/shelltile/commit/441c0974f2045cc36a23beccd1b2d67e2fa05ba1

along with all the editorconfig changes

Tell me if everything's ok, I've tested it on 3.30 and 3.18

**Comment by martin31821** [comment]
Works fine @emasab

**Pull request closed without merging**
